---bài 1
SELECT TENDEAN, CAST(SUM(THOIGIAN) AS DECIMAL (6,2)) AS 'TONG GIO' FROM DEAN 
INNER JOIN CONGVIEC ON CONGVIEC.MADA = DEAN.MADA
INNER JOIN PHANCONG ON PHANCONG.MADA = CONGVIEC.MADA
GROUP BY TENDEAN
SELECT TENDEAN, CONVERT(DECIMAL(6,2), SUM(THOIGIAN)) AS 'TONG GIO' FROM DEAN 
INNER JOIN CONGVIEC ON CONGVIEC.MADA = DEAN.MADA
INNER JOIN PHANCONG ON PHANCONG.MADA = CONGVIEC.MADA
GROUP BY TENDEAN

SELECT TENDEAN, CAST(SUM(THOIGIAN) AS VARCHAR (10)) AS 'TONG GIO' FROM DEAN 
INNER JOIN CONGVIEC ON CONGVIEC.MADA = DEAN.MADA
INNER JOIN PHANCONG ON PHANCONG.MADA = CONGVIEC.MADA
GROUP BY TENDEAN
SELECT TENDEAN, CONVERT(VARCHAR(10), SUM(THOIGIAN)) AS 'TONG GIO' FROM DEAN 
INNER JOIN CONGVIEC ON CONGVIEC.MADA = DEAN.MADA
INNER JOIN PHANCONG ON PHANCONG.MADA = CONGVIEC.MADA
GROUP BY TENDEAN

SELECT TENPHG, CAST(AVG(LUONG) AS DECIMAL(10,2)) AS 'LUONG TRUNG BINH' FROM PHONGBAN 
INNER JOIN NHANVIEN ON NHANVIEN.PHG = PHONGBAN.MAPHG
GROUP BY TENPHG
SELECT TENPHG, CONVERT(DECIMAL(10,2), AVG(LUONG)) AS 'LUONG TRUNG BINH' FROM PHONGBAN 
INNER JOIN NHANVIEN ON NHANVIEN.PHG = PHONGBAN.MAPHG
GROUP BY TENPHG

SELECT TENPHG, CAST(AVG(LUONG) AS VARCHAR(10)) AS 'LUONG TRUNG BINH',
LEFT(CAST(AVG(LUONG) AS VARCHAR(10)),3) + 
REPLACE(CAST(AVG(LUONG) AS VARCHAR(10)),LEFT(CAST(AVG(LUONG) AS VARCHAR(10)),3),',')
FROM PHONGBAN 
INNER JOIN NHANVIEN ON NHANVIEN.PHG = PHONGBAN.MAPHG
GROUP BY TENPHG
SELECT TENPHG, CONVERT(VARCHAR(10), AVG(LUONG)) AS 'LUONG TRUNG BINH',
LEFT(CONVERT(VARCHAR(10), AVG(LUONG)),3) + 
REPLACE(CAST(AVG(LUONG) AS VARCHAR(10)),LEFT(CONVERT(VARCHAR(10), AVG(LUONG)),3),',')
FROM PHONGBAN 
INNER JOIN NHANVIEN ON NHANVIEN.PHG = PHONGBAN.MAPHG
GROUP BY TENPHG
 --Bài 2
 SELECT TENDEAN, SUM(THOIGIAN) AS 'TONG GIO',
CEILING(SUM(THOIGIAN)) AS 'TONG GIO LAM VIEC'
FROM DEAN
INNER JOIN CONGVIEC ON CONGVIEC.MADA = DEAN.MADA
INNER JOIN PHANCONG ON PHANCONG.MADA = CONGVIEC.MADA
GROUP BY TENDEAN

SELECT TENDEAN, SUM(THOIGIAN) AS 'TONG GIO',
FLOOR(SUM(THOIGIAN)) AS 'TONG GIO LAM VIEC'
FROM DEAN
INNER JOIN CONGVIEC ON CONGVIEC.MADA = DEAN.MADA
INNER JOIN PHANCONG ON PHANCONG.MADA = CONGVIEC.MADA
GROUP BY TENDEAN

SELECT TENDEAN, SUM(THOIGIAN) AS 'TONG GIO',
ROUND(CAST(SUM(THOIGIAN) AS DECIMAL(6,2)),2) 'TONG GIO LAM VIEC'
FROM DEAN
INNER JOIN CONGVIEC ON CONGVIEC.MADA = DEAN.MADA
INNER JOIN PHANCONG ON PHANCONG.MADA = CONGVIEC.MADA
GROUP BY TENDEAN

SELECT HONV+' '+TENLOT+' '+TENNV, LUONG FROM NHANVIEN
WHERE LUONG >= (SELECT ROUND(AVG(LUONG),2) FROM NHANVIEN
INNER JOIN PHONGBAN ON PHONGBAN.MAPHG = NHANVIEN.PHG
WHERE TENPHG = N'Nghiên cứu')

--Bài 3
SELECT UPPER(HONV) AS 'HO NV', TENLOT, TENNV, DCHI, COUNT(MA_NVIEN) AS 'SO THAN NHAN' FROM NHANVIEN
INNER JOIN THANNHAN  ON THANNHAN.MA_NVIEN = NHANVIEN.MANV
GROUP BY HONV, TENLOT, TENNV, DCHI
HAVING COUNT(MA_NVIEN) >=2

SELECT HONV, LOWER(TENNV) AS 'TEN LOT', TENNV, DCHI, COUNT(MA_NVIEN) AS 'SO THAN NHAN' FROM NHANVIEN
INNER JOIN THANNHAN  ON THANNHAN.MA_NVIEN = NHANVIEN.MANV
GROUP BY HONV, TENLOT, TENNV, DCHI
HAVING COUNT(MA_NVIEN) >=2

SELECT 
LOWER(LEFT(TENNV,1)) + UPPER(SUBSTRING(TENNV,2,1)) + SUBSTRING(TENNV,3,LEN(TENNV)-2),
COUNT(MA_NVIEN) AS 'SO THAN NHAN' FROM NHANVIEN
INNER JOIN THANNHAN  ON THANNHAN.MA_NVIEN = NHANVIEN.MANV
GROUP BY HONV, TENLOT, TENNV, DCHI
HAVING COUNT(MA_NVIEN) >=2

SELECT DCHI,LEFT(DCHI,CHARINDEX(' ',DCHI)) AS 'SO NHA' FROM NHANVIEN

SELECT DCHI,SUBSTRING(DCHI,CHARINDEX(',',DCHI),9) AS 'THANH PHO' FROM NHANVIEN

SELECT DCHI,SUBSTRING(DCHI,CHARINDEX(' ',DCHI),CHARINDEX(',',DCHI) - 3) AS 'TEN DUONG' FROM NHANVIEN

SELECT TENPHG,TRPHG,B.TENNV, COUNT(A.MANV) AS 'SOLUONG'
FROM NHANVIEN A 
INNER JOIN PHONGBAN ON PHONGBAN.MAPHG = A.PHG
INNER JOIN NHANVIEN B ON  B.MANV = PHONGBAN.TRPHG
GROUP BY TENPHG, TRPHG, B.TENNV
--Bài 4
SELECT * FROM NHANVIEN 
WHERE YEAR(NGSINH) >=196 AND YEAR(NGSINH) <= 1965

SELECT *, YEAR(GETDATE()) - YEAR(NGSINH) AS 'TUOI' FROM NHANVIEN

SELECT *,DATENAME(WEEKDAY,NGSINH) AS 'THU' FROM NHANVIEN

SELECT TENPHG, TRPHG, B.TENNV, NG_NHANCHUC, COUNT(A.MANV) AS 'SO LUONG NV', 
CONVERT(VARCHAR, NG_NHANCHUC , 105) AS 'NGAY NHAN CHUC'
FROM NHANVIEN A
INNER JOIN PHONGBAN ON PHONGBAN.MAPHG = A.PHG
INNER JOIN NHANVIEN B ON B.MANV = PHONGBAN.TRPHG
GROUP BY TENPHG, TRPHG, NG_NHANCHUC,B.TENNV
